const CHECK_USER_SESSION = 'CHECK_USER_SESSION';
const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const SIGN_OUT_START = 'SIGN_OUT_START';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_OUT_FAILURE = 'SIGN_IN_FAILURE';
const SIGN_UP_START = 'SIGN_UP_START';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export default {
  CHECK_USER_SESSION,
  GOOGLE_SIGN_IN_START,
  EMAIL_SIGN_IN_START,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
  SIGN_OUT_START,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_FAILURE,
  SIGN_UP_START,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
};
