const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';

export default {
  GOOGLE_SIGN_IN_START,
  EMAIL_SIGN_IN_START,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
};
